# Generated by Django 2.2 on 2019-05-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190507_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userr',
        ),
    ]
