# Generated by Django 2.2.1 on 2019-05-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_List',
        ),
    ]
