# Generated by Django 2.2 on 2019-04-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
