# Generated by Django 2.2.1 on 2019-05-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
