# Generated by Django 2.2.1 on 2019-05-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190507_1301'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
    ]
