# Generated by Django 2.2 on 2019-04-30 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190430_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 9, 58, 25, 893893)),
        ),
    ]
