# Generated by Django 2.2.1 on 2019-05-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190506_0529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
