# Generated by Django 2.2 on 2019-05-07 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190507_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 9, 57, 28, 432432)),
        ),
    ]
